name: cleanup-buckets

on:
  workflow_dispatch:

jobs:
  cleanup-buckets:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取所有 tag 信息

      - name: Cleanup Buckets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # 删除所有 release
          releases=$(gh release list --limit 1000 | cut -f 1)

          if [ -z "$releases" ]; then
            echo ">>> No releases found."
          else
            for tag in $releases; do
              echo ">>> Deleting Release: $tag"
              gh release delete "$tag" --yes
            done
          fi

          # 删除所有远程分支
          tags=$(git ls-remote --tags origin | awk -F'/' '{print $3}' | grep -v '\^{}')

          if [ -z "$tags" ]; then
            echo ">>> No tags found."
          else
            for tag in $tags; do
              echo ">>> Deleting remote tag: $tag"
              git push origin :refs/tags/"$tag"
            done
          fi
